### PR TITLE
📝 Update debt fund tax rules post 2023 budget

### PR DESCRIPTION
**Pull request by oxalorg**
- Small remark worth fixing!

### CODE REVIEW

**Comment by oxalorg** [comment]
@cla-bot I accept

**Comment by oxalorg** [comment]
@cla-bot check again

**Comment by oxalorg** [comment]
I accept the CLA

**Comment by VineetRDiscord** [comment]
check again

**Comment by VineetRDiscord** [comment]
@cla-bot check again

**Comment by oxalorg** [comment]
@cla-bot I accept the CLA

**Comment by VineetRDiscord** [comment]
@cla-bot check again

**Comment by takeda-discord** [comment]
@cla-bot check again

**Comment by takeda-discord** [comment]
Thanks @oxalorg and apologies for the clabot trouble. 😅

**Comment by oxalorg** [comment]
@takeda-discord thanks for sorting this out! Hoping to contribute more to the wiki ^_^

**Pull request merged**
