### PR TITLE
Minor typo fix

### PR DESCRIPTION
**Pull request by suhaga15**
The word `have` is missing in the sentence. Minor typo

### CODE REVIEW

**Comment by suhaga15** [comment]
I have read the [contributor license agreement](https://indiainvestments.gitbook.io/content/contributors/what-is-a-contributor-license-agreement-and-why-are-we-using-it) and I accept it

**Comment by crimelabs786** [comment]
Thanks @suhaga15 👍 

@cla-bot please check

**Comment by crimelabs786** [comment]
@cla-bot

**Comment by takeda-discord** [comment]
@cla-bot chan, please check now

**Comment by takeda-discord** [comment]
@cla-bot

**Comment by crimelabs786** [comment]
Thanks @suhaga15 for your contribution. LGTM 👍

**Pull request merged**
